#!/usr/bin/env python3
"""Generate a reviewable update PR description without claiming live validation."""
import re
import sys

tag = sys.argv[1]
if not re.fullmatch(r"v\d{4}\.\d+\.\d+", tag):
    raise SystemExit("Invalid stable tag")
print(f"""## Thinking Path

> - Paperclip manages agent work.
> - Loginom Swarm extends a stable Paperclip version.
> - This fork needs stable security and compatibility updates.
> - Each update must preserve the fork history and its integration contracts.
> - This pull request merges {tag} and records the exact source commit.
> - The server remains unchanged until a separate deployment.

## Linked Issues or Issue Description

**Problem**
The fork must track a supported stable upstream release.

**Proposed Solution**
Merge {tag} and review the compatibility manifest and divergence report.

**Alternatives Considered**
A floating master branch would change production inputs without review.

## What Changed

- Merge the stable release and update the source manifest.
- Archive upstream workflows and retain the fork's manual release boundary.

## Verification

The update job runs the registry check, policy tests, typecheck, application tests,
application build, and production image build before it can open this PR.
Review the job artifacts. Database restore/migration and live integration checks
are still required before deployment.

## Risks

Upstream migrations can prevent application-only rollback. Verify a restored
database first. Inspect new upstream contracts even when the merge is clean.

## Model Used

None — this update description is generated by the reviewed update script.

## Checklist

- [x] The stable upstream commit is recorded.
- [x] Automated update checks completed before PR creation.
- [ ] A human reviewed the divergence and compatibility reports.
- [ ] Database migration and rollback were tested on a restored copy.
- [ ] Live integration checks passed before a separate deployment.
""")
